name: ci
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run pytest
        uses: actions/setup-python@v2
        with:
          python-version: "3.6.9"
      - run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          poetry install
          source .venv/bin/activate
          pytest
